wipe     = true
no-tests = true
add-enum-types = true

[psql]
  sslmode = "disable"
  blacklist = ["gorp_migrations"]
  output = "db/postgres/models"

[mysql]
  dbname  = "go-template"
  host    = "mysql"
  user    = "go-template"
  pass    = "password"
  sslmode = "false"
  blacklist = ["gorp_migrations"]
  port    = 3306
  output = "db/mysql/models"
