wipe     = true
no-tests = true
add-enum-types = true
output = "db/models"

[psql]
  blacklist = ["gorp_migrations"]

[mysql]
  dbname  = "go-template"
  host    = "mysql"
  user    = "go-template"
  pass    = "password"
  sslmode = "false"
  blacklist = ["gorp_migrations"]
  port    = 3306
