services:
  golang:
    container_name: ${SERVICE_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ../:/workspaces
    environment:
      PSQL_DBNAME: ${SERVICE_NAME}
      PSQL_HOST: postgresql
      PSQL_PORT: 5432
      PSQL_USER: ${SERVICE_NAME}
      PSQL_PASS: password
  postgresql:
    env_file:
      - .env
    image: postgres:15rc2-alpine
    restart: always
    environment:
      POSTGRES_USER: ${SERVICE_NAME}
      POSTGRES_PASSWORD: password
      PGPASSWORD: password123
      POSTGRES_DB: ${SERVICE_NAME}
    ports:
      - "5432"
    volumes:
      - "go-template-volume:/var/lib/postgresql/data" # Update this to your project
  postgres-gui:
    image: sosedoff/pgweb
    container_name: "${SERVICE_NAME}-pgweb"
    ports:
      - "8081:8081"
    depends_on:
      - postgresql

volumes:
  go-template-volume: # Update this to your project
