postgres:
    dialect: postgres
    datasource: host=${PSQL_HOST} dbname=${PSQL_DBNAME} user=${PSQL_USER} password=${PSQL_PASS} sslmode=${PSQL_SSLMODE}
    dir: migrations/postgres

mysql:
    dialect: mysql
    datasource: ${DSN}&charset=utf8&parseTime=true
    dir: migrations/my_sql
