postgres-dev:
    dialect: postgres
    datasource: host=${PSQL_HOST} dbname=${DB_NAME} user=${DB_USER} password=${DB_PASS} sslmode=disable
    dir: migrations/postgres

mysql-dev:
    dialect: mysql
    datasource: ${DSN}&charset=utf8&parseTime=true
    dir: migrations/my_sql
